[package]
name = "carade-benchmark"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1", features = ["full"] }
redis = { version = "1", features = ["tokio-comp"] }
clap = { version = "4", features = ["derive", "env"] }
anyhow = "1.0"
